name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Test (Go ${{ matrix.go }} / ${{ matrix.os }})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        go: ["1.23.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet ./...
      - name: Static analysis
        run: go run honnef.co/go/tools/cmd/staticcheck@latest ./...
      - name: Check vulnerabilities
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        run: go test -race -vet=off ./...
      - name: Test (with coverage)
        if: matrix.os == 'ubuntu-latest'
        run: go test -race -vet=off -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_ORG_TOKEN }}
  golangci:
    strategy:
      matrix:
        go: ["1.23.x"]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
